spring.datasource.url=${H2_DB_URL}
spring.datasource.username=${H2_DB_USER}
spring.datasource.password=${H2_DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2

spring.mail.properties.mail.debug=true